# Generated by Django 5.1.1 on 2024-10-09 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandora', '0003_alter_amigurumis_imagen_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('amigurumi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pandora.amigurumis')),
            ],
        ),
    ]
