# Generated by Django 5.1.1 on 2024-10-09 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandora', '0006_alter_carrito_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='user',
        ),
        migrations.AlterField(
            model_name='carrito',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
